DROP TABLE IF EXISTS rankings;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS updatedDate;

CREATE TABLE rankings (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Team TEXT NOT NULL,
  Ranking FLOAT NOT NULL,
  Diff TEXT NOT NULL
);

CREATE TABLE games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Home TEXT NOT NULL,
  Away TEXT NOT NULL,
  HomeScore INTEGER NOT NULL,
  AwayScore INTEGER NOT NULL,
  Time INTEGER NOT NULL
);

CREATE TABLE updatedDate (updatedDate);
